repos:
  # https://github.com/pre-commit/pre-commit-hooks/releases
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: check-executables-have-shebangs
      - id: check-merge-conflict
      - id: check-shebang-scripts-are-executable
      - id: check-symlinks
      - id: destroyed-symlinks
      - id: end-of-file-fixer
      - id: mixed-line-ending
      - id: trailing-whitespace

  # https://github.com/python-jsonschema/check-jsonschema/releases
  - repo: https://github.com/python-jsonschema/check-jsonschema
    rev: 0.28.0
    hooks:
      - id: check-renovate
      - id: check-dependabot
      - id: check-github-actions
      - id: check-github-workflows
